# Server
server.port=4000
spring.application.name=secureshop-backend

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:secureshopdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# JPA / JDBC
spring.jpa.show-sql=false

# Logging
logging.level.root=INFO
logging.level.com.treinamento=DEBUG

app.jwt.secret=super-secret-jwt-key-2024
app.jwt.expiration=86400000
