server.port=3000
spring.datasource.url=jdbc:h2:mem:pedidos
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jackson.property-naming-strategy=SNAKE_CASE
